#MailChimp
MAILCHIMP_API_KEY: 'ebcf90741f1a8977fff51ab20642a50a-us8'

#S3
S3_KEY: 'AKIAIFFQMXEAA552H74A'
S3_SECRET: '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'
S3_REGION: 'us-east-1'
S3_ASSET_URL: 'recoveryanytime-dev.s3-website-us-east-1.amazonaws.com'
S3_BUCKET_NAME: 'recoveryanytime-dev'

